### ISSUE TITLE
Support AMD AMF and VAAPI docker & ffmpeg

### ISSUE THREAD

**Issue by Protektor-Desura** [HaveAGitGat/Tdarr#253]
I would like to see full support for AMD AMF and VAAPI added to ffmpeg and the docker container.

There need to be some changes to the Jellyfin docker. You can not do VAAPI transcoding on Linux without Mesa 20.1+. The Mesa 20.1+ update must be installed in the docker image. I added this to docker and it started working for my RX550 video card.
```
apt-get update && apt-get upgrade -y
apt-get install -y gpg
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu bionic main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-bionic.list
apt-get update
apt-get upgrade -y
```
I also installed amdgpu-pro in the host OS as well. This is needed for AMD AMF as well. Plus for AMD AMF you must install amdgpu-pro on the host OS in Linux. Open source only does decoding on AMD AMF and not sure it does any HEVC. Thus the need for amdgpu-pro for AMD AMF transcoding.

All of this is required for HEVC transcoding. If you don't do this you are limited to H.264 and older transcoding. You will also need to deal with the issue of /dev/dri/card0 being owned by root.video and /dev/dri/renderD128 being owned by root.render in many linux distributions (like Ubuntu 20.04) and older docker bases don't know anything about the render group. Linuxserver has fixed this particular issue so you can look at what they did.

**Comment by HaveAGitGat** [comment]
VAAPI should be working in the latest containers now. Not sure about AMF
https://github.com/HaveAGitGat/Tdarr/issues/397

**Comment by marine1988** [comment]
not working for me :(

![image](https://user-images.githubusercontent.com/6524068/110977335-f6bf6b00-8359-11eb-800e-9914fea6a6f2.png)

**Comment by mefbgil** [comment]
Same - not working for me.  Docker on Ubuntu on Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
![image](https://user-images.githubusercontent.com/16986758/113064389-e2b2a080-9184-11eb-8e84-9d8f710b4796.png)

**Comment by marine1988** [comment]
any news on this matter i try on latest dev build 2.0.10 still not working can you look into it please?

**Comment by dfein38347g** [comment]
Seems like it's related to the LD_LIBRARY_PATH similar to this issue with emby https://issueexplorer.com/issue/linuxserver/docker-emby/41.

After this command vainfo works fine:
```
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:${APP_DIR}"
```

However, the node still doesn't use vaapi for some reason. Hopefully this is a good starting point to make some more progress on this. I'd really like to use tdarr but without vaapi it's unusable for me. Emby works fine out of the box.

**Comment by dfein38347g** [comment]
Ok, I've done some more testing and gotten it working, albeit not in docker.

I created an ubuntu 21.10 lxc, then installed tdarr server and node, following the instructions in the docs. Tested and the hw accel didn't work. Then I installed vainfo. Vainfo shows working accel. Tested a transcode again and it still didn't work. Then I installed ffmpeg (via just apt install ffmpeg), and updated the server and node config to use the ffmpeg path of /usr/bin/ffmpeg. Tested a transcode again....and it worked!

So it seems to work with a standard install of the newest ffmpeg and pointing Tdarr to that ffmpeg location. That leads me to believe this problem is something related to the docker image.

**Comment by Protektor-Desura** [comment]
That would seem to point to the issue being the default ffmpeg used by tdarr is not compiled properly with every single codec supported. This is a problem if you are trying to convert from a lot of different codecs to ones more standard which is kind of the point of Tdarr. So Tdarr needs to redo the ffmpeg to include every single option available for ffmpeg.

**Comment by dfein38347g** [comment]
> 
> 
> That would seem to point to the issue being the default ffmpeg used by tdarr is not compiled properly with every single codec supported. This is a problem if you are trying to convert from a lot of different codecs to ones more standard which is kind of the point of Tdarr. So Tdarr needs to redo the ffmpeg to include every single option available for ffmpeg.

Yeah, I agree. It's either that or some issue with paths and not finding the drivers.

**Comment by Protektor-Desura** [comment]
I would highly recommend looking at Jellyfin ffmpeg since it is compiled with every option out there for ffmpeg.

**Comment by HaveAGitGat** [comment]
VAAPI is working in the dev container, you can test it using:

```
docker pull haveagitgat/tdarr_node_acc:dev
docker run \
    --device=/dev/dri:/dev/dri \
    haveagitgat/tdarr_node_acc:dev \
    /bin/bash \
    -c 'curl \
            -o /tmp/sample.mkv \
            -l https://samples.tdarr.io/api/v1/samples/sample__1080__libx264__aac__30s__video.mkv; \
        ffmpeg \
            -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 \
            -hwaccel_output_format vaapi \
            -i /tmp/sample.mkv \
            -c:v:0 hevc_vaapi \
            /tmp/sample-out.mkv'
```

You can see the Docker file here:
https://github.com/HaveAGitGat/Tdarr/blob/master/Dockerfile

Not sure if changes would be needed for AMF but suggestions are welcome

**Comment by HaveAGitGat** [comment]
> I would highly recommend looking at Jellyfin ffmpeg since it is compiled with every option out there for ffmpeg.

Ok I'll have a look at that thanks.

**Comment by Protektor-Desura** [comment]
AMF is supported in the Jellyfin ffmpeg version.

**Comment by HaveAGitGat** [comment]
Didn't have time to add AMF for 2.00.12 but VAAPI should be working. Will add AMF in this week.

**Comment by HaveAGitGat** [comment]
I've added jellyfin ffmpeg to the images so you can now use amf:
https://github.com/HaveAGitGat/Tdarr/blob/7a12fd2601f0739b9b83540da4fd43ef657a7277/Dockerfile#L37

**Comment by Enigma0** [comment]
@HaveAGitGat I am not seeing that amf appears to be enabled:

```
PS C:\Tdarr\Tdarr_Node\node_modules\@ffmpeg-installer\win32-x64> .\ffmpeg.exe -version
ffmpeg version N-92722-gf22fcd4483 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181201
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 24.101 / 56. 24.101
libavcodec     58. 42.102 / 58. 42.102
libavformat    58. 24.101 / 58. 24.101
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 46.101 /  7. 46.101
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100

PS C:\Tdarr\Tdarr_Node\node_modules\@ffmpeg-installer\win32-x64> .\ffmpeg.exe -hwaccels
ffmpeg version N-92722-gf22fcd4483 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 42.102 / 58. 42.102
  libavformat    58. 24.101 / 58. 24.101
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100

Hardware acceleration methods:
cuda
dxva2
qsv
d3d11va
qsv
cuvid
```

**Comment by Protektor-Desura** [comment]
According to that even VAAPI isn't available either.

**Comment by Enigma0** [comment]
This is on win32 where vaapi I believe is not available (may be wrong there). Even so, adding "amf' to the options list per node so they can be defined as amf workers would be a huge help. I plan to just use them for thorough health checks as the transcoding capability isn't as good but still useful.

The right params just need to be passed along: `-hevc_amf` in this case.
