### ISSUE TITLE
handbrake path not working on macOS in 2.00.01

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#330]
**Describe the bug**
Testing Tdarr_Node 2.00.01 on macOS Big Sur 11.1 (Intel x86_64).  Using HandBrakeCLI 1.3.3.  The path is correct but Tdarr returns `Binary test 1: handbrakePath not working: null`.

Full Terminal Log:
`[2021-01-26T09:07:30.897] [INFO] Tdarr_Node - Tdarr_Node listening at http://localhost:8267
[2021-01-26T09:07:31.196] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2021-01-26T09:07:31.199] [INFO] Tdarr_Node - handbrakePath:/users/jasonsansone/Desktop/tdarr/HandBrakeCLI
[2021-01-26T09:07:31.202] [INFO] Tdarr_Node - ffmpegPath:/users/jasonsansone/Desktop/tdarr/ffmpeg
[2021-01-26T09:07:31.206] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2021-01-26T09:07:31.206] [ERROR] Tdarr_Node - Binary test 1: handbrakePath not working: null
[2021-01-26T09:07:31.207] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working`

When HandBrakeCLI is executed on its own:
`jasonsansone@home-desktop / % /users/jasonsansone/Desktop/tdarr/HandBrakeCLI         
[09:07:46] Compile-time hardening features are enabled
[09:07:46] hb_init: starting libhb thread
[09:07:46] thread 7000063ec000 started ("libhb")
Missing input device. Run /users/jasonsansone/Desktop/tdarr/HandBrakeCLI --help for syntax.

HandBrake has exited.`

**To Reproduce**
Install Tdarr_Node 2.00.01 on macOS Big Sur and attempt to launch Tdarr_Node.

**Expected behavior**
Binary should clear tests.

**Screenshots**
N/A

**Desktop (please complete the following information):**
macOS Big Sur 11.1

**Comment by HaveAGitGat** [comment]
Does it work when transcoding?

**Comment by HaveAGitGat** [comment]
I think this is just a faulty test, it should work fine when transcoding.

I don't have a mac and I was testing for 'Run HandBrakeCLI' in the output which is what it gives on linux. I've updated the test so this should be fixed in 2.00.01.

**Comment by jasonsansone** [comment]
> just a faulty test, it should work fine when transcoding.
> 
> I don't have a mac and I was testing for 'Run HandBrakeCLI' in the output which is what it gives on linux. I've updated the test so this should be fixed in 2.00.01.

I am trying to pull your newest build of 2.00.01 but I keep getting
`[2021-01-26T11:20:22.497] [INFO] Tdarr_Updater - Tdarr_Node | Tdarr_Node_darwin_x64_2.00.01.zip already exists!`

Where is the temp location for `Tdarr_Node_darwin_x64_2.00.01.zip` so I can delete it and re-download it?

**Comment by HaveAGitGat** [comment]
It’s in the ‘.staging’ folder in the same folder as Tdarr_Updater. It’s a hidden folder due to the ‘.’ at the start.

**Comment by jasonsansone** [comment]
The tested still doesn't work on 2.00.01 release.

`[2021-01-27T09:24:35.535] [INFO] Tdarr_Node - Starting Tdarr_Node
Preparing environment
[2021-01-27T09:24:35.557] [INFO] Tdarr_Node - Tdarr_Node listening at http://localhost:8267
[2021-01-27T09:24:35.775] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2021-01-27T09:24:35.778] [INFO] Tdarr_Node - handbrakePath:/users/jasonsansone/Desktop/tdarr/HandBrakeCLI
[2021-01-27T09:24:35.781] [INFO] Tdarr_Node - ffmpegPath:/users/jasonsansone/Desktop/tdarr/ffmpeg
[2021-01-27T09:24:35.785] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2021-01-27T09:24:35.786] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2021-01-27T09:24:35.786] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2021-01-27T09:24:35.786] [ERROR] Tdarr_Node - Binary test 1: handbrakePath not working
[2021-01-27T09:24:35.786] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2021-01-27T09:24:37.590] [INFO] Tdarr_Node - Node registered
`

**Comment by jasonsansone** [comment]
> I think this is just a faulty test, it should work fine when transcoding.
> 
> I don't have a mac and I was testing for 'Run HandBrakeCLI' in the output which is what it gives on linux. I've updated the test so this should be fixed in 2.00.01.

Sorry for delay.  I was finally able to actually deploy this node to my cluster in order to test if HandBrake works even when the test fails.  It appears to work fine, it is just an issue with the test.

**Comment by jasonsansone** [comment]
Persists in 2.00.03.

`[2021-01-31T08:21:53.684] [INFO] Tdarr_Node - Starting Tdarr_Node
Preparing environment
[2021-01-31T08:21:53.896] [INFO] Tdarr_Node - Updating plugins
[2021-01-31T08:21:53.897] [INFO] Tdarr_Node - Cloning plugins
[2021-01-31T08:21:53.902] [INFO] Tdarr_Node - Tdarr_Node listening at http://localhost:8267
[2021-01-31T08:21:54.539] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2021-01-31T08:21:54.543] [INFO] Tdarr_Node - handbrakePath:/users/jasonsansone/Desktop/tdarr/HandBrakeCLI
[2021-01-31T08:21:54.547] [INFO] Tdarr_Node - ffmpegPath:/users/jasonsansone/Desktop/tdarr/ffmpeg
[2021-01-31T08:21:54.551] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2021-01-31T08:21:54.551] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2021-01-31T08:21:54.551] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2021-01-31T08:21:54.551] [ERROR] Tdarr_Node - Binary test 1: handbrakePath not working
[2021-01-31T08:21:54.551] [INFO] Tdarr_Node - ---------------Binary tests end-------------------`

**Comment by gjannece** [comment]
I am getting the same error. I am on Ubuntu 20.04. My worker nodes have completely stop from it. 

`root@tdarr-movies:/opt/new-Tdarr/Tdarr_Node# HandBrakeCLI
[04:26:00] Nvenc version 11.0

[04:26:00] hb_init: starting libhb thread
[04:26:00] thread 7f083426b700 started ("libhb")
Missing input device. Run HandBrakeCLI --help for syntax.

HandBrake has exited.
root@tdarr-movies:/opt/new-Tdarr/Tdarr_Node#


root@tdarr-movies:/opt/new-Tdarr/Tdarr_Node# dpkg -l |grep andbr
ii  handbrake-cli                        1:1.3.3.1-zhb-1ppa1~focal1                  amd64        versatile DVD ripper and video transcoder - command line
ii  handbrake-gtk                        1:1.3.3.1-zhb-1ppa1~focal1                  amd64        versatile DVD ripper and video transcoder - GTK GUI`

**Comment by gjannece** [comment]
info button in webUI shows this:

`

Path: | blahblahshow - S01E06 - What's Eating Uncle Jake WEBDL-1080p.mkv
-- | --
CLI: | HandBrake
Preset: | --scan
Process reasons: |  

`

**Comment by HaveAGitGat** [comment]
@gjannece I think your issue is different to the original issue in this thread. This issue was about the test failing on macOS which yours does not relate to.

On the linux Node make sure to set the HandBrake path in `Tdarr_Node_Config.json`

http://tdarr.io/docs/installation

**Comment by jasonsansone** [comment]
Fixed in 2.00.06.  Closing.

**Comment by HaveAGitGat** [comment]
Great, thanks for the feedback.
