### ISSUE TITLE
commas in filenames are not treated correctly, causes error (Win64)

### ISSUE THREAD

**Issue by andbir** [HaveAGitGat/Tdarr#467]
**Describe the bug**
Running on Windows10 64bit 21H1 (v19043.110)  with included FFmpeg version. Output set to same as input. Transcode cache set to B:/. Problem: Files with commas in the filenames are causing target files to not be written.

Try to reencode TV show YOU episodes to H.265. input Filenames are for example:
Z:/TVshows/YOU/Season 2/You - S02E04 - The Good, the Bad, & the Hendy WEBDL-1080p.mkv
Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv

**Expected behavior**
I want the output file to be written, and would like for it to have the same file name as the original file, including commas.

**Screenshots**

**Please provide the following information:**

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

[2021-07-30T22:38:34.670] [WARN] Tdarr_Node - Tdarr ALERT: NO OUTPUT FILE PRODUCED:  
B:/Warehouse 13 - S04E05 - No Pain, No Gain Bluray-1080p-TdarrCacheFile-xjoCAND3D.mkv
[2021-07-30T22:49:35.805] [WARN] Tdarr_Node - Tdarr ALERT: NO OUTPUT FILE PRODUCED:  
B:/Watchmen - S01E04 - If You Don't Like My Story, Write Your Own WEBDL-1080p-TdarrCacheFile-amEeInd0q.mkv
[2021-07-30T23:05:30.875] [WARN] Tdarr_Node - Tdarr ALERT: NO OUTPUT FILE PRODUCED:  
B:/The Good, the Bad and the Ugly (1966) Bluray-1080p-TdarrCacheFile-Yicd5ZHkI.mkv

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

Unable to find a suitable output format for 'Z:/TVshows/YOU/Season'
Z:/TVshows/YOU/Season: Invalid argument
Tdarr ALERT: NO OUTPUT FILE PRODUCED:
B:/You - S01E08 - You Got Me, Babe WEBDL-1080p-TdarrCacheFile-gdephivQ3.mkv

Usually windows requires filenames that contain spaces to be enclosed in "" when provided to the OS. But to allow for special characters according to https://docs.microsoft.com/sv-se/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces the filename can be altered so that it starts with \\?\ to disable all further processing of the filename contents and the supplied filename to be sent directly to the underlying filesystem.

However this seems to NOT be the problem,  if I look at the command line that Tdarr is trying to send to ffmpeg the filename has been truncated at the comma BEFORE reaching FFMpeg and the file system; 

C:/Program Files (x86)/Tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe -y -i Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv -map 0:2 Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me B:/You - S01E08 - You Got Me, Babe WEBDL-1080p-TdarrCacheFile-gdephivQ3.mkv

(look at the end of the second time the filename is given in the command line, it is cut off after "Me".

Indeed if I alter the command line manually and execute it in a CMD shell to read like this: 

"c:/Program Files (x86)/Tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe" -y -i "Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv" -map 0:2 "Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080x.mkv" "B:/You - S01E08 - You Got Me, Babe WEBDL-1080p-TdarrCacheFile-gdephivQ3.mkv"

it runs okay. (had to alter the 1080p to 1080x otherwise it told me that the input and output filename could not be the same, I guess there should be a qdephivQ3 somewhere in this second filename as well, and that they are renamed to the final filename once the reencoding is accepted by Tdarr

XML snap
"_id": "Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv",
  "file": "Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv",
....
"SourceFile": "Z:/TVshows/YOU/Season 1/You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv",
    "errors": [],
    "Duration": 2701.344,
    "DefaultDuration": 0.032,
    "ExifToolVersion": 12.21,
    "FileName": "You - S01E08 - You Got Me, Babe WEBDL-1080p.mkv",
    "Directory": "Z:/TVshows/YOU/Season 1",
    "FileSize": "2.2 GiB",

**Comment by supersnellehenk** [comment]
What's happening here is that Tdarr uses the comma to separate the arguments being passed to ffmpeg by a plugin. `//For FFmpeg, the input arguments come first followed by a comma, followed by the output argument.` https://github.com/HaveAGitGat/Tdarr_Plugins So this would require a rewrite how this is handled.

**Comment by HaveAGitGat** [comment]
@supersnellehenk no it's not to do with that. That's only for the ffmpeg trascode arguments and you can use `<io>` instead of a comma to fix that.

@andbir which Tdarr version are you using? I think this bug was fixed a long time ago. Filenames with commas in are working fine for me on .09 on Windows: 

![image](https://user-images.githubusercontent.com/43864057/128404573-09c8ad77-74ec-47fa-b204-39e8dea97500.png)

**Comment by tehniemer** [comment]
I think I'm having a similar problem, anywhere in the file path that a comma exists the transcode fails.

Here's my list of failures.
![image](https://user-images.githubusercontent.com/11021632/129606296-73be6a9b-fc19-46d5-8c2d-3b6fcef35dbe.png)

and the info log from the last failure
```
NodeID: PLEX

Command:

ffmpeg -y -i /temp/Avatar - The Last Airbender - S03E19 - Chapter Nineteen - Sozin's Comet, Part 2 - The Old Masters-TdarrCacheFile-H_2Ji6BG8.mkv -map 0:2 /media/Television/Anime/Avatar - The Last Airbender (2005)/Season 3/Avatar - The Last Airbender - S03E19 - Chapter Nineteen - Sozin s Comet /temp/Avatar - The Last Airbender - S03E19 - Chapter Nineteen - Sozin's Comet, Part 2 - The Old Masters-TdarrCacheFile-mVCzF5Ypb.mkv

Last 200 lines of CLI log:

0.0 size= 691693kB time=00:23:27.55 bitrate=4025.7kbits/s speed=1.33x

frame=33760 fps= 32 q=-0.0 size= 691693kB time=00:23:28.36 bitrate=4023.4kbits/s speed=1.33x

frame=33776 fps= 32 q=-0.0 size= 691693kB time=00:23:29.00 bitrate=4021.5kbits/s speed=1.33x

frame=33794 fps= 32 q=-0.0 size= 691693kB time=00:23:29.79 bitrate=4019.3kbits/s speed=1.33x

frame=33809 fps= 32 q=-0.0 size= 691693kB time=00:23:30.41 bitrate=4017.5kbits/s speed=1.33x

frame=33827 fps= 32 q=-0.0 size= 691693kB time=00:23:31.17 bitrate=4015.3kbits/s speed=1.33x

frame=33845 fps= 32 q=-0.0 size= 692014kB time=00:23:31.77 bitrate=4015.5kbits/s speed=1.33x

frame=33863 fps= 32 q=-0.0 size= 692014kB time=00:23:32.47 bitrate=4013.5kbits/s speed=1.33x

frame=33878 fps= 32 q=-0.0 size= 692014kB time=00:23:33.24 bitrate=4011.3kbits/s speed=1.33x

frame=33893 fps= 32 q=-0.0 size= 692014kB time=00:23:34.01 bitrate=4009.1kbits/s speed=1.33x

frame=33908 fps= 32 q=-0.0 size= 692014kB time=00:23:34.52 bitrate=4007.7kbits/s speed=1.33x

frame=33925 fps= 32 q=-0.0 size= 692014kB time=00:23:35.10 bitrate=4006.1kbits/s speed=1.33x

frame=33938 fps= 32 q=-0.0 size= 692014kB time=00:23:35.74 bitrate=4004.2kbits/s speed=1.33x

frame=33953 fps= 32 q=-0.0 size= 694460kB time=00:23:36.51 bitrate=4016.2kbits/s speed=1.33x

frame=33971 fps= 32 q=-0.0 size= 694460kB time=00:23:37.02 bitrate=4014.8kbits/s speed=1.33x

frame=33987 fps= 32 q=-0.0 size= 694460kB time=00:23:37.91 bitrate=4012.2kbits/s speed=1.33x

frame=34004 fps= 32 q=-0.0 size= 694460kB time=00:23:38.53 bitrate=4010.5kbits/s speed=1.33x

frame=34022 fps= 32 q=-0.0 size= 694460kB time=00:23:39.26 bitrate=4008.4kbits/s speed=1.33x

frame=34037 fps= 32 q=-0.0 size= 694460kB time=00:23:39.75 bitrate=4007.0kbits/s speed=1.33x

frame=34051 fps= 32 q=-0.0 size= 694460kB time=00:23:40.54 bitrate=4004.8kbits/s speed=1.33x

frame=34067 fps= 32 q=-0.0 size= 694460kB time=00:23:41.03 bitrate=4003.4kbits/s speed=1.33x

frame=34082 fps= 32 q=-0.0 size= 697095kB time=00:23:41.69 bitrate=4016.8kbits/s speed=1.33x

frame=34100 fps= 32 q=-0.0 size= 697095kB time=00:23:42.46 bitrate=4014.6kbits/s speed=1.33x

frame=34118 fps= 32 q=-0.0 size= 697095kB time=00:23:43.23 bitrate=4012.4kbits/s speed=1.33x

frame=34133 fps= 32 q=-0.0 size= 697095kB time=00:23:43.87 bitrate=4010.6kbits/s speed=1.33x

frame=34151 fps= 32 q=-0.0 size= 697095kB time=00:23:44.63 bitrate=4008.5kbits/s speed=1.33x

frame=34165 fps= 32 q=-0.0 size= 697095kB time=00:23:45.19 bitrate=4006.9kbits/s speed=1.33x

frame=34181 fps= 32 q=-0.0 size= 697095kB time=00:23:46.11 bitrate=4004.3kbits/s speed=1.33x

frame=34199 fps= 32 q=-0.0 size= 699703kB time=00:23:46.62 bitrate=4017.9kbits/s speed=1.33x

frame=34216 fps= 32 q=-0.0 size= 699703kB time=00:23:47.24 bitrate=4016.1kbits/s speed=1.33x

frame=34235 fps= 32 q=-0.0 size= 699703kB time=00:23:48.03 bitrate=4013.9kbits/s speed=1.33x

frame=34250 fps= 32 q=-0.0 size= 699703kB time=00:23:48.79 bitrate=4011.7kbits/s speed=1.33x

frame=34266 fps= 32 q=-0.0 size= 699703kB time=00:23:49.43 bitrate=4009.9kbits/s speed=1.33x

frame=34283 fps= 32 q=-0.0 size= 699703kB time=00:23:50.20 bitrate=4007.8kbits/s speed=1.33x

frame=34301 fps= 32 q=-0.0 size= 699703kB time=00:23:50.97 bitrate=4005.6kbits/s speed=1.33x

frame=34315 fps= 32 q=-0.0 size= 702233kB time=00:23:51.59 bitrate=4018.4kbits/s speed=1.33x

frame=34333 fps= 32 q=-0.0 size= 702233kB time=00:23:52.12 bitrate=4016.9kbits/s speed=1.33x

frame=34352 fps= 32 q=-0.0 size= 702233kB time=00:23:53.13 bitrate=4014.1kbits/s speed=1.33x

frame=34370 fps= 32 q=-0.0 size= 702233kB time=00:23:53.64 bitrate=4012.6kbits/s speed=1.33x

frame=34385 fps= 32 q=-0.0 size= 702233kB time=00:23:54.41 bitrate=4010.5kbits/s speed=1.33x

frame=34403 fps= 32 q=-0.0 size= 702233kB time=00:23:55.24 bitrate=4008.2kbits/s speed=1.33x

frame=34421 fps= 32 q=-0.0 size= 702233kB time=00:23:55.90 bitrate=4006.3kbits/s speed=1.33x

frame=34436 fps= 32 q=-0.0 size= 704731kB time=00:23:56.41 bitrate=4019.1kbits/s speed=1.33x

frame=34454 fps= 32 q=-0.0 size= 704761kB time=00:23:57.24 bitrate=4017.0kbits/s speed=1.33x

frame=34471 fps= 32 q=-0.0 size= 704761kB time=00:23:57.88 bitrate=4015.2kbits/s speed=1.33x

frame=34487 fps= 32 q=-0.0 size= 704761kB time=00:23:58.84 bitrate=4012.5kbits/s speed=1.33x

frame=34505 fps= 32 q=-0.0 size= 704761kB time=00:23:59.61 bitrate=4010.4kbits/s speed=1.33x

frame=34520 fps= 32 q=-0.0 size= 704761kB time=00:24:00.12 bitrate=4009.0kbits/s speed=1.33x

frame=34535 fps= 32 q=-0.0 size= 704761kB time=00:24:00.63 bitrate=4007.5kbits/s speed=1.33x

frame=34550 fps= 32 q=-0.0 size= 704761kB time=00:24:01.27 bitrate=4005.8kbits/s speed=1.33x

frame=34565 fps= 32 q=-0.0 size= 707439kB time=00:24:02.04 bitrate=4018.8kbits/s speed=1.33x

frame=34580 fps= 32 q=-0.0 size= 707439kB time=00:24:02.55 bitrate=4017.4kbits/s speed=1.33x

frame=34595 fps= 32 q=-0.0 size= 707439kB time=00:24:03.07 bitrate=4016.0kbits/s speed=1.33x

frame=34613 fps= 32 q=-0.0 size= 707439kB time=00:24:04.03 bitrate=4013.3kbits/s speed=1.33x

frame=34631 fps= 32 q=-0.0 size= 707439kB time=00:24:04.79 bitrate=4011.2kbits/s speed=1.33x

frame=34649 fps= 32 q=-0.0 size= 707439kB time=00:24:05.56 bitrate=4009.0kbits/s speed=1.33x

frame=34667 fps= 32 q=-0.0 size= 707439kB time=00:24:06.33 bitrate=4006.9kbits/s speed=1.33x

frame=34685 fps= 32 q=-0.0 size= 709868kB time=00:24:06.84 bitrate=4019.3kbits/s speed=1.33x

frame=34703 fps= 32 q=-0.0 size= 709868kB time=00:24:07.74 bitrate=4016.8kbits/s speed=1.33x

frame=34712 fps= 32 q=-0.0 Lsize= 714633kB time=00:24:07.82 bitrate=4043.5kbits/s speed=1.33x

video:691233kB audio:22645kB subtitle:12kB other streams:0kB global headers:0kB muxing overhead:

0.104130%

[aac @ 0x562b5ee5d180] Qavg: 463.306

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3

libavutil 56. 31.100 / 56. 31.100

libavcodec 58. 54.100 / 58. 54.100

libavformat 58. 29.100 / 58. 29.100

libavdevice 58. 8.100 / 58. 8.100

libavfilter 7. 57.100 / 7. 57.100

libswscale 5. 5.100 / 5. 5.100

libswresample 3. 5.100 / 3. 5.100

libpostproc 55. 5.100 / 55. 5.100

Input #0, matroska,webm, from '/temp/Avatar - The Last Airbender - S03E19 - Chapter Nineteen - Sozin's Comet, Part 2 - The Old Masters-TdarrCacheFile-H_2Ji6BG8.mkv':

Metadata:

JBDONEDATE :

2021-08-16T17:13:30.416Z

JBDONEVERSION : 1

ENCODER : Lavf58.29.100

Duration: 00:24:07.88, start: 0.000000, bitrate: 4043 kb/s

Chapter #0:0: start 0.000000, end 600.000000

Metadata:

title : CHAPTER 1

Chapter #0:1: start 600.000000, end 1200.000000

Metadata:

title : CHAPTER 2

Chapter #0:2: start 1200.000000, end 1446.000000

Metadata:

title : CHAPTER 3

Chapter #0:3: start 1446.000000, end 1447.884000

Metadata:

title : CHAPTER 4

Stream #0:0(eng): Video: hevc, yuv420p10le(tv), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)

Metadata:

ENCODER : Lavc58.54.100 hevc_vaapi

BPS-eng : 3910939

DURATION-eng : 00:24:07.883708333

NUMBER_OF_FRAMES-eng: 34712

NUMBER_OF_BYTES-eng: 707822849

_STATISTICS_WRITING_APP-eng: mkvpropedit v45.0.0 ('Heaven in Pennies') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-08-16 17:32:16

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:1(eng): Audio: aac, 48000 Hz, stereo, fltp (default)

Metadata:

title : Stereo

ENCODER : Lavc58.54.100 aac

BPS-eng : 128128

DURATION-eng : 00:24:07.828000000

NUMBER_OF_FRAMES-eng: 67867

NUMBER_OF_BYTES-eng: 23188480

_STATISTICS_WRITING_APP-eng: mkvpropedit v45.0.0 ('Heaven in Pennies') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-08-16 17:32:16

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:2(eng): Subtitle: subrip (default)

Metadata:

title : SDH

BPS-eng : 68

DURATION-eng : 00:23:20.750000000

NUMBER_OF_FRAMES-eng: 366

NUMBER_OF_BYTES-eng: 11918

_STATISTICS_WRITING_APP-eng: mkvpropedit v45.0.0 ('Heaven in Pennies') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-08-16 17:32:16

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

[NULL @ 0x5618fd28ec00] Unable to find a suitable output format for '/media/Television/Anime/Avatar'

/media/Television/Anime/Avatar: Invalid argument

Tdarr ALERT: NO OUTPUT FILE PRODUCED:

/temp/Avatar - The Last Airbender - S03E19 - Chapter Nineteen - Sozin's Comet, Part 2 - The Old Masters-TdarrCacheFile-mVCzF5Ypb.mkv
```

**Comment by HaveAGitGat** [comment]
This is is an odd one as I have copy and pasted the exact same file names and it has worked fine (on Windows) so not sure if there are some Windows shenanigans going on.

**Comment by tehniemer** [comment]
I'm still having a lot of issues with commas in file paths. Many, if not all of my files that have a comma somewhere in the file path are failing. I'm running the server and two nodes in docker on Debian systems. It seems that the paths are being truncated after and including the comma. Below is an example

Actual file path:
```
/data/Media/Television/Series/Umbrella Academy, The (2019) [imdb-tt1312171]/Season 02/The Umbrella Academy (2019) - S02E07 - Öga for Öga [WEBDL-1080p][8bit][x264][EAC3 5.1]-GHOSTS.mkv
```

Command from infolog
```
Command:
ffmpeg -y -i /data/Tdarr/Cache/The Umbrella Academy (2019) - S02E07 - Öga for Öga [WEBDL-1080p][8bit][x264][EAC3 5.1]-GHOSTS-TdarrCacheFile-wqvAgPcTV.mkv -map 0:2 /data/Media/Television/Series/Umbrella Academy /data/Tdarr/Cache/The Umbrella Academy (2019) - S02E07 - Öga for Öga [WEBDL-1080p][8bit][x264][EAC3 5.1]-GHOSTS-TdarrCacheFile-ujh4hEbMA.mkv
```

**Comment by HaveAGitGat** [comment]
I have named a folder and file with that exact name and it has completed successfully on Windows:

![image](https://user-images.githubusercontent.com/43864057/156525193-99f3d279-2aed-4e7b-924f-fc37c1c4092d.png)

Same thing when running Docker linux_x64:
![image](https://user-images.githubusercontent.com/43864057/156526280-efccdaa5-2722-4037-8dc9-93e7f432e9e8.png)

**Comment by tehniemer** [comment]
Could it be related to a specific plugin and not Tdarr itself?

**Comment by HaveAGitGat** [comment]
Potentially, I used these ones in the test above: 
![image](https://user-images.githubusercontent.com/43864057/156701665-4dfbe0fb-df89-41d4-b6f8-c1388c1184d4.png)

**Comment by HaveAGitGat** [comment]
Haven't heard any issues of this on recent versions so reopen if needed ty.
