### ISSUE TITLE
"The encoder 'truehd' is experimental but experimental codecs are not enabled,"

### ISSUE THREAD

**Issue by janipewter** [HaveAGitGat/Tdarr#542]
**Describe the bug**
Using the plugin "Tdarr_Plugin_00td_action_standardise_audio_stream_codecs" to standardise audio codec. When selecting truehd or dca, the transcode always fails with the error **The encoder 'dca' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.**

**To Reproduce**
Simply put the plugin into your transcode options and try to transcode a file.

**Expected behavior**
That is would do what it says in the description.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
server config:

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
- 
> {
>   "serverPort": "8266",
>   "webUIPort": "8265",
>   "serverIP": "192.168.10.20",
>   "handbrakePath": "",
>   "ffmpegPath": ""
> }

node config:

> {
>   "nodeID": "Quadro P1000",
>   "nodeIP": "192.168.10.20",
>   "nodePort": "8267",
>   "serverIP": "192.168.10.20",
>   "serverPort": "8266",
>   "handbrakePath": "",
>   "ffmpegPath": "",
>   "mkvpropeditPath": "",
>   "pathTranslators": [
>     {
>       "server": "",
>       "node": ""
>     }
>   ]
> }

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

> NodeID: Quadro P1000
> 
> Command:
> 
> ffmpeg -i /mnt/tv/Sound Tests/a/Dolby TrueHD & Atmos Chameleon.m2ts -map 0:v -map 0:a -map 0:s? -map 0:d? -c copy -c:a:0 dca -c:a:1 dca -c:a:2 dca -c:a:3 dca /temp/Dolby TrueHD & Atmos Chameleon-TdarrCacheFile-228pNsMFd.m2ts
> 
> Last 200 lines of CLI log:
> 
> ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
> 
> built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
> 
> configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
> 
> libavutil 56. 51.100 / 56. 51.100
> 
> libavcodec 58. 91.100 / 58. 91.100
> 
> libavformat 58. 45.100 / 58. 45.100
> 
> libavdevice 58. 10.100 / 58. 10.100
> 
> libavfilter 7. 85.100 / 7. 85.100
> 
> libswscale 5. 7.100 / 5. 7.100
> 
> libswresample 3. 7.100 / 3. 7.100
> 
> libpostproc 55. 7.100 / 55. 7.100
> 
> [hevc @ 0x556fa7997f40] Skipping NAL unit 62
> 
> [mpegts @ 0x556fa7990a80] stream 0 : no PTS found at end of file, duration not set
> 
> [mpegts @ 0x556fa7990a80] stream 1 : no PTS found at end of file, duration not set
> 
> Input #0, mpegts, from '/mnt/tv/Sound Tests/a/Dolby TrueHD & Atmos Chameleon.m2ts':
> 
> Duration: 00:01:02.78, start: 11.650667, bitrate: 81438 kb/s
> 
> Program 1
> 
> Stream #0:0[0x1011]: Video: hevc (Main 10) (HDMV / 0x564D4448), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9],
> 
> 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc
> 
> Stream #0:1[0x1015]: Video: hevc (Main 10) (HDMV / 0x564D4448), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc
> 
> Stream #0:2[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 7.1, s32 (24 bit)
> 
> Stream #0:3[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s
> 
> Stream #0:4[0x1101]: Audio: eac3 (AC-3 / 0x332D4341), 48000 Hz, 7.1, fltp, 1664 kb/s
> 
> Stream #0:5[0x1102]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s
> 
> Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 2, only the last option '-c:a:0 dca' will be used.
> 
> Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 3, only the last option '-c:a:1 dca' will be used.
> 
> Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 4, only the last option '-c:a:2 dca' will be used.
> 
> Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 5, only the last option '-c:a:3 dca' will be used.
> 
> Stream mapping:
> 
> Stream #0:0 -> #0:0 (copy)
> 
> Stream #0:1 -> #0:1 (copy)
> 
> Stream #0:2 -> #0:2 (truehd (native) -> dts (dca))
> 
> Stream #0:3 -> #0:3 (ac3 (native) -> dts (dca))
> 
> Stream #0:4 -> #0:4 (eac3 (native) -> dts (dca))
> 
> Stream #0:5 -> #0:5 (ac3 (native) -> dts (dca))
> 
> Press [q] to stop, [?] for help
> 
> [dca @ 0x556fa7ce6080]
> 
> The encoder 'dca' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
> 
> Conversion failed!

 - OS: UnRaid 6.9.2
 - Browser Chrome 97
 - Version 2.00.13

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks, fixed here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/257

Restart Tdarr or click 'Update community plugins' on the plugins tab and it should dnow be woking

**Comment by janipewter** [comment]
Hi, thanks, also have the same issue with **Tdarr_Plugin_00td_action_keep_one_audio_stream**

**Comment by HaveAGitGat** [comment]
Thanks, fixed: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/258

**Comment by Vinny-cz** [comment]
Hello,
I have up to date Tdarr but still getting this error:


2023-07-27T13:15:32.282Z [truehd @ 0x55dfafb310c0] The encoder 'truehd' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

112

2023-07-27T13:15:32.282Z

113

2023-07-27T13:15:32.282Z Conversion failed!

When im looking at plugin cycle snapshots, in the command the ' -strict -2' parameter is missing.

Command:

tdarr-ffmpeg -i "/mnt/media/DOWNLOADS/Guardians Of The Galaxy Vol. 2 (2017) /Guardians.Of.The.Galaxy.Vol..2..mkv" -c copy -map 0:v -map 0:1 -c:1 truehd -map 0:s? -map 0:d? -max_muxing_queue_size 9999 /temp/Guardians.Of.The.Galaxy.Vol..2.-TdarrCacheFile-QGNA8zRyc.mkv

what am I setting wrong?

Thanks

**Comment by Vinny-cz** [comment]
Hello,
I have up to date Tdarr but still getting this error:

2023-07-27T13:15:32.282Z [truehd @ 0x55dfafb310c0] The encoder 'truehd' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

112

2023-07-27T13:15:32.282Z

113

2023-07-27T13:15:32.282Z Conversion failed!

When im looking at plugin cycle snapshots, in the command the ' -strict -2' parameter is missing.

Command:

tdarr-ffmpeg -i "/mnt/media/DOWNLOADS/Guardians Of The Galaxy Vol. 2 (2017) /Guardians.Of.The.Galaxy.Vol..2..mkv" -c copy -map 0:v -map 0:1 -c:1 truehd -map 0:s? -map 0:d? -max_muxing_queue_size 9999 /temp/Guardians.Of.The.Galaxy.Vol..2.-TdarrCacheFile-QGNA8zRyc.mkv

what am I setting wrong?

Thanks
