### ISSUE TITLE
Plugins not read by server (ENOENT error)

### ISSUE THREAD

**Issue by gmhowell** [HaveAGitGat/Tdarr#588]
**Describe the bug**
Plugins are sometimes not read by the Tdarr Server

**To Reproduce**
Create a new plugin by adding the file to the local plugins directory. This is inconsistent. It has happened twice using the plugin creator and once when using a file created on the system with a text editor, but did not occur another time when a plugin was created with the text editor.

**Expected behavior**
Tdarr should read and implement the plugin without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/32222057/161159604-629c9f18-3e0f-4974-a418-e10c22c054cd.png)

**Please provide the following information:**
- Server config:
- {
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO"
}

- Log files  
- [2022-03-31T22:09:51.861] [INFO] Tdarr_Server - eBJ8MWrB-: Sending files for scanning, library :eBJ8MWrB-

[2022-03-31T22:10:56.727] [ERROR] Tdarr_Server - Error: ENOENT: no such file or directory, open '/opt/Tdarr/server/Tdarr/Plugins/Local/undefined.js'

at Object.openSync (fs.js:497:3)

at Object.openSync (pkg/prelude/bootstrap.js:739:32)

at Object.readFileSync (fs.js:393:35)

at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)

at readPluginText (/snapshot/be/srcug/plugins/pluginFuncs.js:1:9648)

at /snapshot/be/srcug/api/mainApi.js:1:25141

at _0x44a4b2 (/snapshot/be/srcug/api/mainApi.js:1:6070)

at Object.next (/snapshot/be/srcug/api/mainApi.js:1:4372)

at /snapshot/be/srcug/api/mainApi.js:1:3836

at new Promise (<anonymous>)

at /snapshot/be/srcug/api/mainApi.js:1:3203

at /snapshot/be/srcug/api/mainApi.js:1:24882

at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5)

at next (/snapshot/be/node_modules/express/lib/router/route.js:137:13)

at Route.dispatch (/snapshot/be/node_modules/express/lib/router/route.js:112:3)

at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5) {

errno: -2,

syscall: 'open',

code: 'ENOENT',

path: '/opt/Tdarr/server/Tdarr/Plugins/Local/undefined.js'

}

[2022-03-31T22:12:07.165] [INFO] Tdarr_Server - /opt/Tdarr/configs/Tdarr_Server_Config.json

[2022-03-31T22:12:07.214] [INFO] Tdarr_Server - {

serverPort: '8266',

webUIPort: '8265',

serverIP: '0.0.0.0',

handbrakePath: '',

ffmpegPath: '',

logLevel: 'INFO'

}

 - OS: Linux (Ubuntu 21.10)
 - Browser chrome
 - Version (of browser or Tdarr?) Tdarr: 2.00.16

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks, just to check, does the same read-error issue happen when you refresh the page or does that fix it?

**Comment by VanillaThunda** [comment]
Hi Guys,
I just ran into this problem myself and wanted to contribute some information from my point of view.

I am running version 2.00.16 on Windows 10 and have also created a few simple plugins myself, which Tdarr can not read after creating them.

In the Tdarr Webinterface it simply is shown as "Read Error" with the name of the .js:
![image](https://user-images.githubusercontent.com/103832672/163675727-e709cfc4-e351-43d1-92b9-aa447d64b37b.png)

When I click on "Edit" the "Tdarr_Server.exe" window shows this message:
![image](https://user-images.githubusercontent.com/103832672/163675755-d7f541f5-0827-41e7-b0a0-8b1edfc37831.png)
<details>[2022-04-16T14:23:03.659] [ERROR] Tdarr_Server - Error: ENOENT: no such file or directory, open 'D:/Tools/Tdarr_Updater/server/Tdarr/Plugins/Local/undefined.js'
    at Object.openSync (fs.js:497:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at Object.readFileSync (fs.js:393:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)
    at readPluginText (C:\snapshot\be\srcug\plugins\pluginFuncs.js:1:9899)
    at C:\snapshot\be\srcug\api\mainApi.js:1:25053
    at _0x2ca782 (C:\snapshot\be\srcug\api\mainApi.js:1:6263)
    at Object.next (C:\snapshot\be\srcug\api\mainApi.js:1:4568)
    at C:\snapshot\be\srcug\api\mainApi.js:1:4039
    at new Promise (<anonymous>)
    at C:\snapshot\be\srcug\api\mainApi.js:1:3403
    at C:\snapshot\be\srcug\api\mainApi.js:1:24792
    at Layer.handle [as handle_request] (C:\snapshot\be\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\snapshot\be\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\snapshot\be\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\snapshot\be\node_modules\express\lib\router\layer.js:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:/Tools/Tdarr_Updater/server/Tdarr/Plugins/Local/undefined.js'
}</details>

I already tried to restart the Node and Server Services (Both run on the same PC) and I copy/pasted the .js-File from the "Local" to the "Community"-Folder hoping I coult trick Tdarr out a bit. But Tdarr also can not read the file.

I attach one of the created Plugin-files, mybe someone could check it and see if there is a problem with it. (I Had to zip it)
[CPeKaXCUM.zip](https://github.com/HaveAGitGat/Tdarr/files/8499947/CPeKaXCUM.zip)

Thanks and greetings from Germany!

**Comment by HaveAGitGat** [comment]
Hi this is fixed in .17.

Can use the pre-release now with: 

docker.io/haveagitgat/tdarr_acc:dev
docker.io/haveagitgat/tdarr_node_acc:dev

Will be released fully today/tomorrow.

**Comment by VanillaThunda** [comment]
> 

Nice, thanks a lot!

**Comment by HaveAGitGat** [comment]
On windows you can use 2.00.17 with this method FYI: https://docs.tdarr.io/docs/releases/pre-releases#using-a-native-package-pre-release

**Comment by VanillaThunda** [comment]
@HaveAGitGat 

I just tested the new .17 Version and the Bug still exists. New generated Plugins still show up as "Read Error" but the error message when clicking on "edit" is a bit different:
![image](https://user-images.githubusercontent.com/103832672/163681586-50457a47-c631-43ed-8fda-d1e277c39998.png)

![image](https://user-images.githubusercontent.com/103832672/163681544-f072b8e0-ff92-4a02-ac46-19c5cc80db49.png)
 
<details>[2022-04-16T17:41:34.204] [ERROR] Tdarr_Server - [Error: ENOENT: no such file or directory, open 'D:\Tools\Tdarr_Updater\server\Tdarr\Plugins\Local\null.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Tools\\Tdarr_Updater\\server\\Tdarr\\Plugins\\Local\\null.js'
}</details>

**Comment by HaveAGitGat** [comment]
@VanillaThunda that’s on Windows right? Made quite a few changes this week so think they might not be in that windows package as I have to build it manually (last built it on Wednesday or so). 

Should be working fine in the containers and Linux packages as they were built today.

**Comment by VanillaThunda** [comment]
@HaveAGitGat alright, thanks for the fast response. I will keep an eye on it.
I guess the built will be available for Windows in the next few days?

**Comment by HaveAGitGat** [comment]
@VanillaThunda re-download the windows packages, they’re now up to date 👍.

**Comment by VanillaThunda** [comment]
@HaveAGitGat seems like its been working now. Thanks a lot for all the work!
Do you have a donation link or something where I can buy you a beer?

**Comment by HaveAGitGat** [comment]
Great 🙂, and don’t worry about it. Let me know if you have any further issues, thanks.

**Comment by joshoram80** [comment]
Is the Docker file and code updated yet? I'm building image using newer version of FFMPEG-Jellyfin that fixes garbage encodes on TGL and Vaapi.

**Comment by HaveAGitGat** [comment]
@joshoram80 which jellyfin ffmpeg version?

**Comment by joshoram80** [comment]
4.4.1-2. You had it in Master branch a few commits back but it got
reverted. It seems to have helped with corrupted transcodes on Nuc11 for
me. I was using your Dockerfile from .16 with the rpm install changed to
pull that version.

If I do that again, will it pull your latest .17 code into the newly built
image, it the old code? I've had problems with the plugin Read Error from
time to time as well that you have fixed, but I'd like to keep using
4.4.1-2 so I don't trash my files with bad encodes.

**Comment by HaveAGitGat** [comment]
@joshoram80 yeah I've updated the docker files so just do the same thing again for .18
