### ISSUE TITLE
Closed Captions not detected - "Unable to run CCExtractor"

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#686]
My Tdarr is not detecting Closed Captions anymore.
I believe it may have something to do with this error message that I get on the media details:

"closedCaptionRead":""Unable to run CCExtractor"". I have 2.00.18 Pro, running on Docker in Raspberry PI OS ARMv7.

![image](https://user-images.githubusercontent.com/35738729/190435309-40cc9688-ff23-49dd-b723-32def63aabc6.png)

Any tips? Maybe an executable that needs to be updated/replaced?
Any commands I can run to check why it's failing?

Thanks!

**Comment by wsegatto** [comment]
Anyone?

**Comment by wsegatto** [comment]
This is the output from ffmpeg -i:
![image](https://user-images.githubusercontent.com/35738729/216998388-d34d1a51-6155-41ef-86f4-f6382815e44a.png)

**Comment by HaveAGitGat** [comment]
The purpose of using CCExtractor in Tdarr is to detect closed captions because at the time, FFmpeg/FFprobe seemed to miss some. I think they are much better at detecting closed captions now so not sure CCExtractor is needed anymore. Will need to do some testing with the new FFmpeg/FFprobe versions. Would make things a lot easier to not have CCExtractor.

**Comment by wsegatto** [comment]
Thank you @HaveAGitGat for the info. 
But in the time being closed captions are not detected for me in Tdarr and the community plugin (which I tweeked with the help of supersnellehenk) and my local one are not working anymore. I don't know why, this presence of Closed Captions is not shown in the files details. :(

**Comment by HaveAGitGat** [comment]
Which method are you using to check? Should be something like this:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/db3fecab6a7789817cf124430894fec941638040/Community/Tdarr_Plugin_x7ac_Remove_Closed_Captions.js#L42

**Comment by HaveAGitGat** [comment]
Hmm yeah seems new ffmpeg still isn't detecting some closed captions which isn't ideal.

![image](https://user-images.githubusercontent.com/43864057/217196484-168199df-ebda-4ce4-b1ef-990980d1749b.png)

**Comment by wsegatto** [comment]
Hi @HaveAGitGat, following up here, is there anything we can do about this?
I have two shows with Closed Captions and I can't get rid of them without manually running ffmpeg when I know they have this issue.

**Comment by HaveAGitGat** [comment]
Tried using https://packages.ubuntu.com/focal/ccextractor in the Docker image but it's on version 0.87 which does not seem to pickup the closed caption in the test file I have.

The manual download version I've been using for linux x64 is 0.88 but can't quite remember where I got it.

Ideally would use 0.94 https://github.com/CCExtractor/ccextractor/releases

Seems only Debian Sid has all 0.94 available: 
https://pkgs.org/download/ccextractor

**Comment by HaveAGitGat** [comment]
Fixed in containers for 2.00.20

Can use here:
haveagitgat/tdarr_acc:dev_2.00.20_2023_03_31T09_52_29z

**Comment by HaveAGitGat** [comment]
2.00.20 released

**Comment by gouthamravee** [comment]
Tdarr is adding the line below to all my files from what I can see, is this related?

```
"scannerReads":{
"closedCaptionRead":""Unable to run CCExtractor exit code 10""
}
```

**Comment by keithing** [comment]
FYI if anyone else stumbled upon this like I did, I believed the error of my job was due to the line I saw that read  `"closedCaptionRead":""Unable to run CCExtractor exit code 1""`.  However, this is because I was directly clicking on the failed job.  Instead, to see the real error look at the button under `Report`, which will show you the actual Docker worker logs and the correct error codes.

**Comment by SawkeeReemo** [comment]
> Same here (Running `2.00.20` natively on `MacOS Ventura`):
> 
> ```
> "root":{
>     ...
>     "hasClosedCaptions":false
>     "container":"mkv"
>     "scannerReads":{
>         "ffProbeRead":"success"
>         "exiftoolRead":"success"
>         "mediaInfoRead":"success"
>         "closedCaptionRead":""Unable to run CCExtractor exit code 1""
>     }
> ...
> ```
> 
> This is because there was no CCExtrator installed on my machine, so here's how to solve that in case anybody else needs it.
> 
> Since [the official brew install fails](https://github.com/CCExtractor/ccextractor/issues/1534), for those interested, [you can build CCExtrator yourself](https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD) to solve this issue.
> 
> Here is what I run on my `Apple M1 Pro`:
> 
> ```
> brew install pkg-config autoconf automake libtool tesseract leptonica
> git clone https://github.com/CCExtractor/ccextractor.git
> cd ccextractor/Mac
> pkg-config --exists --print-errors tesseract
> pkg-config --exists --print-errors lept
> export LIBRARY_PATH="/opt/homebrew/lib" (won't need this unless you're on arm)
> export CPATH="/opt/homebrew/include" (won't need this unless you're on arm)
> ./build.command OCR
> cp ./ccextractor ~/bin/ (make sure this is in your $PATH on `~/.zshrc` or `~/.bashrc~)
> ```
> 
> Don't forget to add the path on `Tdarr_Server_Config.json` and `Tdarr_Node_Config.json`:
> 
> ```
> {
>   ...
>   "ccextractorPath": "/Users/YOUR_USER/bin/ccextractor",
>   ...
> }
> ```

I did all this on macOS 10.15.7 (Catalina) on my old Mac Pro trash can, and I still get this error:
`CCExtractor not working:"Unable to run CCExtractor exit code 2"`
Any ideas?
